services:
    minio_client:
        class: 'Aws\S3\S3Client'
        arguments:
            -  endpoint: 'http://127.0.0.1:9000'
               use_path_style_endpoint: true
               region: 'default'
               version: 'latest'
               credentials:
                   key: '%env(MINIO_ACCESS_KEY)%'
                   secret: '%env(MINIO_SECRET_KEY)%'


flysystem:
    storages:
        opendxp.asset.storage:
            adapter: 'aws'
            visibility: public
            options:
                client: 'minio_client'
                bucket: 'asset'
        opendxp.asset_cache.storage:
            adapter: 'aws'
            visibility: public
            options:
                client: 'minio_client'
                bucket: 'assetcache'
        opendxp.thumbnail.storage:
            adapter: 'aws'
            visibility: public
            options:
                client: 'minio_client'
                bucket: 'thumbnail'
        opendxp.version.storage:
            adapter: 'aws'
            visibility: public
            options:
                client: 'minio_client'
                bucket: 'version'
        opendxp.recycle_bin.storage:
            adapter: 'aws'
            visibility: public
            options:
                client: 'minio_client'
                bucket: 'recyclebin'
        opendxp.admin.storage:
            adapter: 'aws'
            visibility: public
            options:
                client: 'minio_client'
                bucket: 'admin'
        opendxp.email_log.storage:
            adapter: 'aws'
            visibility: public
            options:
                client: 'minio_client'
                bucket: 'emaillog'
        opendxp.temp.storage:
            adapter: 'aws'
            visibility: public
            options:
                client: 'minio_client'
                bucket: 'temp'
        opendxp.application_log.storage:
            adapter: 'aws'
            visibility: public
            options:
                client: 'minio_client'
                bucket: 'applicationlog'