doctrine_migrations:
    connection: default
    migrations_paths:
        'OpenDxp\Bundle\CoreBundle\Migrations': '@OpenDxpCoreBundle/src/Migrations'
    storage:
        table_storage:
            table_name: 'migration_versions'
            version_column_name: 'version'
            version_column_length: 1024
            executed_at_column_name: 'executed_at'
            execution_time_column_name: 'execution_time'
    all_or_nothing: false
    check_database_platform: false
    factories:
        'Doctrine\Migrations\MigrationsRepository': 'OpenDxp\Migrations\FilteredMigrationsRepository'
        'Doctrine\Migrations\Metadata\Storage\MetadataStorage': 'OpenDxp\Migrations\FilteredTableMetadataStorage'



